sudo: required
services:
- docker
before_install:
- docker build -t apptreesoftware/docker-react -f Dockerfile.dev .
script:
- docker run apptreesoftware/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-1-032894678773
  bucket_path: docker-react
  on:
    branch: master
  access_key_id:
    secure: "uoIIJrW5eMECiJuN3ceH755VyY0IotMDEb6GGBkEB8yLnmfXq9F6SnCBIPeO1TQXc3LyMSMGR0M0dN8BF+j3FWq8O432Xgs3LOB5S3nzn5Hbi5EFjC4qRQL4l3ebz6bVnUni0gfDdJH4Ogkb1s6PcXBDkOK9BcZZ5MFJQA6dNQ8Ca/tqCtImOkaPI2JGtqX+0abNDZe1k8Foyby8GeDHcXrth+9Dl8GA4KqypKUlH5DILs/v1hsFMtGFDD+uaUcJPKUWnECcQGF2IEgAt30sBAr1K/mH40HB2QIQu7h7cRbd2LHu9WEBOv/jOO/IaD7HSVCHznsWZ1ZQpxIMRRmuHBtjqc27270aBwkE95NekbfhsUo2hmFhsHyj9a9NyzFjcox0rxocaQENw1y1PU7Sx3PHQd1x6D0MyaqSeF3AofxJCSUfHj4SvX4XlFnjgPYKQPOr2Sd57nx1lKBjPzRaagI9UhUADCvRyn90Op+mrPjQccE1Y8R8S7uSCZUZ7JsOKtEPln/q2bsqPjKPj2ds51ZV2RysJCZIwn4D1IKJPqY96NZl3TohUZ/T47NrT8h8M3KNmgVAu7il4OoDDsWow5ixKCBDDhwE3s0jS6rmonrq2+Sno1OU6o+1Fjo/cY+H80hK39R7ZvZyLDC1RO9tGw4GncVDmUgo6FPFSFYPeUA="
  secret_access_key:
    secure: "0u3FaMZvhfTLQbJLo4NH3r51X/tVteDXSab6RzglsMHFAQg2h4WNv8D405fnb/PXKlaDGxLl2ZPLNhCHnOKqJ8FnGIa/6aWqTS+J9XMhwE021Mp2F9G1YZHpBpKu81btw8Sf7RQutuA/kYlREj9mDkeRk1X3yKq8U8YZrddSNYuNASERuiY0KOut3i9V2PzofLyblStg/MObaaKJVEwtu56AIPVH5ZrIZGH63prhzZBKBobwyMZ4TPwoLx+rY/5tJamhBlO9grFB+IqIP4wL8OVgXbyIP1pTbpsj/Nr2WVZ4K1yTdJ/hPoPB3YIOK+ydQBToB/Dd8EqUqgy5TDlQCRWtz9r/80tDUQPSoiX5UwncjGLhT62NkyrJPhTD8JmRsFN6rEaKhTRraEZ7HlbOHAD3jNRjl5wLQDNOFp9/Yvg34JwrHoh+ULfCOTU6GwT13xAfv4m1bh39kFMno9a3yo89RV9BTIbQwnwMxZZ1pTwiWnu/gVUwLPTPDxsWjnS61ymAJIjMXre/iRgH1azP/2g0HwEKUTTTy3mqU6Bezo0dcoxzNVrqJRcBI06gMhpmDvra7YTKG7jXpj9j3fGnU/6qGKvHPL5+NR2LE6q3x9QVhgeWU2z4Nnk2zunDmj11nP35EMDtcm8PwLC14DIrXOdixiy+74lnpu/J3LirA5Q="
