sudo: required
services:
- docker
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-1-032894678773
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
env:
  global:
    secure: dfRW9XkDUmEMPCDPxWUfVtIh6xxyLCCUXlgbxIesK69CjcRdORRb8Oe0k7MJhOOftJT55FkjYgoHCBlWBP11ZEsJKU5VZKFU7Z1YIeeOjI5Cz3OQQUGp34hjwtKGSLt2kvKFDt+hGR7pB6Nz78qooqcxxKe8GbijX4IjEPQzT8FeAJT9KB1u4ylGZbpDpQ9jJ5hOU3wVMpdGi+Wu96ua7UnnWFkFOsPAM32UB7LcEw8XLGJRRXHxlDl+Nb7gutNr/ahI/JwxTxEifn9veZVFnnOffckWCRQDBAB7SHML10aL5KCoiTVkNR+8+2+3Cr0+oWuML9J3ioEM8IwvFdFi8ojU1ZlddnaI1XdW/PNyNJmMaNty5a7L+6eR5B9+8aIMphr13Obuz2bkGsGjxFY2NyHYhx+Zr/pjfwOskORa//keAXgqcnxTeJFrvRr5psncIM1ybvA3wSHuGqS4cCSiAk5LHwh2+DtzWHOx1X6n7crIBDcsffi8KOrIe7iOdBUtt3XDEGbnPzd5iHMBKaut+kavH89h/jIQoc+R5pOhnmUHt3ozEkuXyHJ39hH3F8Fw6stB+/O3fBExidWyf23VODdXULnjSN6qCX4lLuBJXNui+UuB0G3Cc7Mjx1JfpmJ1Ayi3PZta7VGY9HGw8evghbxAIuCNtHuk2LqtfaFK/1w=
