sudo: required
services:
- docker
before_install:
- docker build -t apptreesoftware/docker-react -f Dockerfile.dev .
script:
- docker run apptreesoftware/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-1-032894678773
  bucket_path: docker-react
  on:
    branch: master
  access_key_id:
    secure: "Eu5qd/T5fYgZfWHQDHwgH/RXKftVJEsl14Ixx4LsQRh9j4GikmSrpffDthpnCN8e1I+LBoLbkMtMp+4l7PICrqnHTup4372enhjXsfhFK9UfSp75x4yZ0wXEPLFMUM8jU2E545P2yLstdRLPBl0OBG+z+wZZI58evb9ODkwBTkq0t6lR8jEhtyVrhYO4c4Q3MnEJgF1RVvefbEOGkqGjmwYvj8IKPXh/1Vj0BcWnx4Vybeh0n00RqWYhCnWKCZ7nkNJs6XHibQwR4DKAHs0A/eJBv1M3OHBW+gGunt7hX+QzaYCqoDrhNzF3C4YmXsK5C4eegFmHaDG/lbn6lzLFQZk1icLzxz2BiLOWM+nI90LKGHP5Zptnlj4TwF5b26eT7sceQaNqn/oG9Rw8+VzzM6coTgRURd/iMfAdCk6ikgV95rzbOsFwFU2YC2RqPZO9DfiNOf8pI8KWD230fS0C6JoTY7z4Cdfk8jOHIthAVeHlQfZ0p1TOU46E64awVtUqI65Ox35w6u3gTZTi1fpTSROiFy5WCPUzvGkmFS+XrINn9ExLjm1l4l18pTwEzHjAm1lUgGLiaWfeNNzH9lW0sEAjLXbrvc8+Z0fl933pDEeKn2sMMeWEVDcc19UFgzIz3pnaXi2fXIstMsXa+5LJN2opniIdhK0IF8VfQmA41KI="
  secret_access_key:
    secure: "KPHpJelSQC+BuWW8DfGt4PsJuavPNcUGIb21wll/MfT1Gu2nB6Q28xhjgVzRHv3vFik8CQ1UApRkwiC5rtH5rfpmjXtnSB4cYQY2rQQGeAWrByTg/MBRFMaQcYD1vAUgYNzSNHkvcZaa7zNdnbMx14VREPlQ1qox+kdWVseOXP7bFA+UCUauATQc6C1qazfWjMM5s1619VXL0QqB4Va47xWfbzSBJaG+veIMB+ciA3T6Td9YqAoDB28wDYM91sjGIsLu4iK584LI1Cb5xYaE0200fm3IjVSJgDtggjN88m6AMCjVm0QA8N6dULHMnP7HvesQHAWUw5Y9NUDJpYO0sWB9S7KKcTsXtlfHrbmQr95Yma0AXnnUImRK8I4Az1plvyJRossFF2WpBqQ+SNxXLQZ+F1S7Ud+X5S3HHuDVXensTvNeNbo5Y0PaX2yDJFmEXSiBVi/1U0mshrVJegE1Hwm1mD/JsSsm6+l8e47TYRxEils/kxfAcOzyJcPlBVXxPnsAyFZKU7o8fGvffSt5Afe17pVogBWndP4g9cODP0DnFmLQPOgzuGcggRPUWInaEugb/Xjj98gBvSOSJUwMH4DrwYoYZTlJ0Va0JF3OEktSNHronVaUiD+lXZELHy3l21lC7A/QoMefftxGaR9vQ2xusyFtzAZpR1t4oTU+LZM="
