sudo: required
services:
  - docker

before_install:
  - docker build -t apptreesoftware/docker-react -f Dockerfile.dev .

script:
  - docker run apptreesoftware/docker-react npm run test -- --coverage